rabbitmq:
  url: "amqp://guest:guest@localhost:5672/"
  queue_name: "video_processing"
mongodb:
  url: "mongodb://localhost:27017"
  database: "video_processing_db"
  collection_results: "processing_results"
postgresql:
  host: "localhost"
  port: 5432
  user: "postgres"
  password: "password"
  database: "video_processing_db"
  table_status: "processing_status"
log_path: "video_analizer.log"
debug: true