env: "local"
storage_path: "host=localhost port=5334 user=postrges password=postrges dbname=postrges sslmode=disable"
http_server:
  address: "localhost:8086"
  timeout: 4s
  idle_timeout: 60s
  user: "admin"
  password: "admin"