rabbitmq:
  url: "amqp://guest:guest@rabbitmq:5672"
  queue_name: "video_processing"
mongodb:
  url: "mongodb://mongo:27017"
  database: "video_processing_db"
  collection_results: "collection_results"
postgresql:
  host: "postgres"
  port: 5432
  user: "postgres"
  password: "password"
  database: "video_processing_db"
  table_status: "processing_status"
port: 8080
log_path: "video_analizer.log"
debug: true