services:
  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672" # для Celery
      - "15672:15672" # для доступа к RabbitMQ Management UI

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379:6379"

  celery_worker:
    build: .
    container_name: celery-worker
    command: celery -A app.tasks worker --loglevel=info
    depends_on:
      - rabbitmq
      - redis
    volumes:
      - .:/app
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq:5672//
      - CELERY_BACKEND_URL=redis://redis:6379/0

  flower:
    image: mher/flower
    container_name: flower
    ports:
      - "5555:5555" 
    depends_on:
      - rabbitmq
      - redis
    environment:
      - CELERY_BROKER_URL=amqp://guest@rabbitmq:5672//
      - CELERY_BACKEND_URL=redis://redis:6379/0

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: qioto
      MONGO_INITDB_ROOT_PASSWORD: qwerty

