version: '3.8'

services:
  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres:16.1-alpine3.19
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: video_processing_db
    ports:
      - "5577:5432"
    # volumes:
      # - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: video-processing-backend
  #   restart: always
  #   ports:
  #     - "8082:8080"
  #   environment:
  #     MONGO_URL: mongodb://mongo:27017
  #     POSTGRES_HOST: postgres
  #     POSTGRES_PORT: 5432
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: video_processing_db
  #     RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
  #   depends_on:
  #     - mongo
  #     - postgres
  #     - rabbitmq

volumes:
  mongo_data:
  postgres_data: